name: Build

on: [push]

jobs:
  build:

    strategy: 
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, macos-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # [UBUNTU ONLY BEGIN] -------------------------------------------------------------
      - name: Install C++ Compiler Tool Chain [UBUNTU]
        run: sudo apt-get install -y gcc make cmake clang-format clang-tidy
        if: matrix.os == 'ubuntu-latest'

      - name: Install Portaudio Dependency chain [UBUNTU]
        run: sudo apt-get install -y doxygen pulseaudio libboost-all-dev graphviz
        if: matrix.os == 'ubuntu-latest'
        
      # -------------------------------------------------------------------------------

      # [MACOS ONLY BEGIN] ------------------------------------------------------------
      - name: Install Portaudio Dependency chain [MACOS]
        run: brew install jack doxygen
        if: matrix.os == 'macos-latest'

      # -------------------------------------------------------------------------------
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Arduino PlatformIO Project
        run: |
          cd arduino
          pio run

      - name: Build Visualizer Project 
        run: | 
          cd visualizer 
          ./build
          
